#!/bin/bash

# DevA - Web Development Environment
# Created by Miguel Nunes
# https://github.com/mignz/DevA

# ------------------------------------------------------------------------------

# Confirmation

dialog --clear \
    --title "Backup Notice" \
    --backtitle "DevA > Backup" \
    --yesno "For the entire backup and restore process to work without issues you should update every package and DevA to their latest versions. When you restore this backup, the installed packages will be the same version.\n\nTo check for updates, select 'No' and go to the action 'Check for updates'." \
    11 70
# shellcheck disable=SC2105
[ $? -eq 1 ] && continue

# ------------------------------------------------------------------------------

# Prompt location

# shellcheck disable=SC2154
if [ "$os" == "macos" ]; then
    defpath=/Users/$(whoami)/Desktop
else
    defpath=/home/$(whoami)/Desktop
fi
# shellcheck disable=SC2154
backuploc=$(dialog --clear \
    --title "Backup Location" \
    --backtitle "DevA > Backup" \
    --inputbox "Where should the backup file go?\n\nWhat will be saved:\n- Website Files inside $(cat "$path_etc/nginx/deva/deva_www")\n- MySQL databases\n- MongoDB databases\n- Nginx host files\n\nMake sure the file ends with the \".tar\" extension:" \
    16 70 \
    "$defpath/DevA-Backup-$(date +%Y%m%d).tar" \
    3>&1 1>&2 2>&3 3>&-)
# shellcheck disable=SC2105
[ $? -eq 1 ] && continue
clear
[ -z "${backuploc// }" ] && backuploc=~/Desktop/DevA-Backup-$(date +%Y%m%d).tar
if [ ! -d "$(dirname "$backuploc")" ]; then
    red "The specified directory does not exist! Press any key to continue ..."
    yellow "Directory: $backuploc"
    wait_keypress
    # shellcheck disable=SC2105
    continue
fi

# ------------------------------------------------------------------------------

# Prepare

yellow "Starting backup ..."
if [ "$os" == "macos" ]; then
    brew services start mysql
    brew services stop mongodb
    path_mongodata=/usr/local/var/mongodb
    node_pkg=node
    ver_sql=$(vcurrent mysql)
    ver_composer=$(vcurrent composer)
    # shellcheck disable=SC2154
    phalcon=$phpversion-phalcon
else
    sudo service mysql start
    sudo service mongodb stop
    path_mongodata=/var/lib/mongodb
    node_pkg=nodejs
    ver_sql=$(vcurrent mysql-server | cut -d " " -f 1)
    ver_composer=$(composer --version | cut -d " " -f 3)
    phalcon=php-phalcon
fi

# ------------------------------------------------------------------------------

# Backup databases

mysqldump -uroot --all-databases > ~/deva_backup_mysql.sql
cd ~ && tar zcf ~/deva_backup_mysql.tar.gz deva_backup_mysql.sql &
cd $path_mongodata && sudo tar zcf ~/deva_backup_mongodb.tar.gz . &

# ------------------------------------------------------------------------------

# Backup website data

cd "$(cat "$path_etc/nginx/deva/deva_www")" && tar zcf ~/deva_backup_websites.tar.gz . &

# ------------------------------------------------------------------------------

# Backup hosts

cd "$path_etc/nginx/deva/vhosts" && tar zcf ~/deva_backup_nginx.tar.gz . &

# ------------------------------------------------------------------------------

# Create backup token

# shellcheck disable=SC2154
echo -e "Confirmation that this backup file was created by DevA (Release: $this_update)\n\nDate: $(date).\n\nNginx: $(vcurrent nginx)\nPHP: $(vcurrent "$phpversion")\nPhalcon: $(vcurrent $phalcon)\nMySQL: $ver_sql\nNode: $(vcurrent $node_pkg)\nMongoDB: $(vcurrent mongodb)\nComposer: $ver_composer" > ~/deva_backup_token.txt &
wait

# ------------------------------------------------------------------------------

# Create tar file

cd ~ && tar --append --file="$backuploc" deva_backup_mysql.tar.gz
cd ~ && tar --append --file="$backuploc" deva_backup_mongodb.tar.gz
cd ~ && tar --append --file="$backuploc" deva_backup_websites.tar.gz
cd ~ && tar --append --file="$backuploc" deva_backup_nginx.tar.gz
cd ~ && tar --append --file="$backuploc" deva_backup_token.txt

# ------------------------------------------------------------------------------

# Remove temp files

rm ~/deva_backup_mysql.sql &
rm ~/deva_backup_mysql.tar.gz &
rm ~/deva_backup_mongodb.tar.gz &
rm ~/deva_backup_websites.tar.gz &
rm ~/deva_backup_nginx.tar.gz &
rm ~/deva_backup_token.txt &
wait

# ------------------------------------------------------------------------------

# Show finish message

if [ "$os" == "macos" ]; then
    md5sum=$(md5 -q "$backuploc")
else
    md5sum=$(md5sum "$backuploc" | cut -d " " -f 1)
fi
dialog --clear \
    --title "Complete!" \
    --backtitle "DevA > Backup" \
    --msgbox "Backup complete!\n\nHere's an MD5 hash of the backup file. You should take note of it and confirm before restoring.\n\n$md5sum" \
    10 70
