#!/bin/bash

# DevA - Web Development Environment
# Created by Miguel Nunes
# https://github.com/mignz/DevA

# ------------------------------------------------------------------------------

# Run brew doctor

clear
yellow "-------------------------------------"
yellow "--- BREW DOCTOR OUTPUT BELOW\n"
blue "You should follow the instructions to fix these issues and\nthen run \"$ brew doctor\" again.\n"
brew doctor
yellow "\n--- BREW DOCTOR OUTPUT ABOVE"
yellow "-------------------------------------\n"
echo -e -n "  \033[1mPress any key to continue ...\033[0;27m"
wait_keypress
