# DevA - Web Development Environment
# Created by Miguel Nunes
# https://github.com/mignz/DevA

# Generated by DevA on PLACEHOLDER_DATE

server {
    include deva/deva_common.conf;
    server_name PLACEHOLDER_NAME;
    root PLACEHOLDER_ROOT;
    include deva/deva_PLACEHOLDER_REWRITE.conf;
}
